# Site settings
title       : alexjanderbacalso.com
description : My personal blog site.
logo        : site-logo.png
search      : true
baseurl     : "" # the subpath of your site, e.g. /blog/
url         : http://localhost:4000
author      : Alexjander T. Bacalso
permalink   : /:title

# Site owner
owner:
  email             : janderbacalso@gmail.com
  facebook_username : alexjander.bacalso
  twitter_username  : xubsolver
  github_username   : xanderdwyl

# Site creator


# Build settings
markdown: kramdown
